[package]
name = "org-roam-rs"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "lib"]

[dependencies]
anyhow = "1.0.96"
emacs = "0.18.0"
orgize = "0.9.0"
rouille = "3.6.2"
rusqlite = "0.33.0"
serde = { version = "1.0.217", features = ["derive"] }
serde_json = "1.0.138"
tantivy = "0.22.0"
tempfile = "3.14.0"

[profile.dev]
debug = 0

[profile.release]
lto = true
codegen-units = 1

[[bin]]
name = "org-roam-rs"
path = "src/bin/main.rs"
