#+html: <div align="center">
* *org-roamers*
*NOTE:* /This is in very early development and not ready for actual
usage./
#+html: </div>
-----

org-roamers is an addition to [[https://github.com/org-roam/org-roam][org-roam]] and a replacement for
[[https://github.com/org-roam/org-roam-ui][org-roam-ui]].

The server requires one argument: the path to the org files:

#+begin_src sh
cargo run --release --bin org-roamers-cli -- --server <Path>
#+end_src

org-roamers tries to be compatible with org-roam, but some hurdles
must be expected. It tries to build the same graph, but internally the
databases differ substantially.

* Docker
The server can also be run inside a docker container. A Dockerfile is
provided in the root of the project. With a working installation of
docker, use the following commands to create a working image.

#+begin_src sh
# build the image
docker build -t org-roamers .
# run the container
docker run -p 5000:5000 -v <ROAM_DIR>:/data -v /etc/org-roamers/:/etc/org-roamers/ org-roamers
#+end_src

* Configuration
** HTML display
Custom environments (e.g. =#+begin_CUSTOM=) can be styled by adding an
entry to the =html_settings.json= configuration (on unix found in
=/etc/org-roamers=). Example:

#+begin_src json
{
  "env_advices": [
    {
      "on": "important",
      "header": "<div style=\"width: 100%; color: var(--warn)\"><b>! important</b></div>",
      "css_style": "border-left: 2px solid var(--warn); padding: 5px; background-color: color-mix(in srgb, var(--warn), var(--surface))",
      "text_styling": "margin-bottom: 0px; margin-top: 5px;"
    }
  ]
}
#+end_src

Explanation:
- =on=: The string on which the exporter checks if the rule applies.
- =header=: Custom header that is inserted before the text.
- =css_style=: Additional styling that is added to the enclosing HTML
  element.

* Testing
All rust based tests can be run with the standard rust command:

#+begin_src sh
cargo test
#+end_src

If any tests fail that are using the =test-data/=, refer to =doc/rebuilding-db.org=.
