#+title: Rebuilding the testing db
#+options: author:nil date:nil toc:nil

The =test-db.db= is the only part of the testing infrastructure, that
cannot be rebuilt by the infrastructure itself. The database is used
to check if =org-roamers= produces the same data as the reference
implementation: org-roam. A rebuild of the database is required if:
- the test data changes
- a new version of org-roam is supported by org-roamers
- new features of org-roam is supported by org-roamers

Rebuilding the database requires a running instance of emacs with
org-roam installed. First set the environment variable =REPO= to the
root of the =org-roamers= repo using =M-x setnev=. Then paste the
following code into the =*scratch*= buffer and call =M-x eval-buffer=:

#+begin_src emacs-lisp
(let* ((base-path (getenv "REPO"))
       (org-roam-db-location (expand-file-name "test-data/test-db.db" base-path))
       (org-roam-directory (expand-file-name "test-data" base-path)))
  (org-roam-db-sync))
#+end_src

Then, commit run all tests and check that none of the tests fail.
Finally, commit the changes to fix the CI.

*NOTE:* The databases uses absolute file paths in the databse, meaning
 that if you push the changes, your local path of the repo can be seen
 by anyone. This does not break CI.
