name: Build and Smoke Test Docker Image

on:
  push:
    branches: [ "**" ]
  pull_request:

jobs:
  docker-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Build Docker image
        run: |
          docker build -t org-roamers-image .

      - name: Run Docker container in background
        run: |
          docker run -d --name org-roamers-container -p 5000:5000 -v ./test-data:/data org-roamers-image

      - name: Wait a few seconds
        run: sleep 5

      - name: Check if container is still running
        run: |
          if [ "$(docker inspect -f '{{.State.Running}}' org-roamers-container)" != "true" ]; then
            echo "Container failed to start or crashed."
            docker logs org-roamers-container
            exit 1
          fi

      - name: Output container logs
        run: docker logs org-roamers-container

      - name: Stop and remove container
        run: |
          docker stop org-roamers-container
          docker rm org-roamers-container
