name: Build Windows Binary

on:
  push:
    branches: [ "**" ]
  pull_request:
    branches: [ "**" ]

jobs:
  build-windows:
    name: Build on Windows (MSVC)
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Rust
      uses: actions-rust-lang/setup-rust-toolchain@v1
      with:
        target: x86_64-pc-windows-msvc

    - name: Build release binary
      run: cargo build --release --bin server

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '22'

    - name: Install dependencies
      run: npm ci
      working-directory: ./web

    - name: Build project
      run: npm run build
      working-directory: ./web

    - name: Upload build artifact
      uses: actions/upload-artifact@v4
      with:
        name: windows-msvc-binary
        path: target/release/server.exe
